enum ActionTypes {
  LOAD_RATES = 'App/LOAD_RATES',
  LOAD_RATES_SUCCESS = 'App/LOAD_RATES_SUCCESS',
  LOAD_RATES_ERROR = 'App/LOAD_RATES_ERROR',

  SET_CURRENCY = 'App/SET_CURRENCY',

  SET_POCKETS = 'App/SET_POCKETS',
}

export default ActionTypes;
